package ru.whoame.recogniser.ui.viewmodel.handler

import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.receiveAsFlow
import ru.whoame.recogniser.ui.viewmodel.contracts.Transaction
import ru.whoame.recogniser.ui.viewmodel.utils.TransactionSenderDslMarker

/**
 * Abstract base class for handling domain events within a state machine architecture.
 * Provides mechanisms to update state and send side effects using coroutine-based transactions.
 *
 * @param State The type representing the state.
 * @param SideEffect The type representing UI or other indirect actions triggered by events.
 * @param DomainEvent The type representing incoming domain events.
 **/
abstract class BaseDomainEventHandler<State : Any, SideEffect : Any, DomainEvent : Any> {

    private val transactionChannel: Channel<Transaction<State, SideEffect, Nothing, DomainEvent>> = Channel()

    /**
     * Flow of all transactions generated by state or side effect changes.
     * These transactions are intended to be processed by observers of the state machine.
     **/
    val transactionFlow: Flow<Transaction<State, SideEffect, Nothing, DomainEvent>>
        get() = transactionChannel.receiveAsFlow()

    /**
     * Processes an incoming domain event and returns a cold [Flow].
     * The data from this [Flow] is completely ignored.
     * Subclasses should provide implementation
     * that determines how each event affects state and/or side effects.
     *
     * Use reduceState functions to update state, and use reduceSideEffect functions to send side effect.
     * They send data to the channel that handles the updates.
     *
     * @param event Incoming domain-specific event to handle.
     *
     * @return [Flow] that produces results, the result itself is completely ignored.
     **/
    abstract fun handleEvent(event: DomainEvent): Flow<*>

    /**
     * Reduces (updates) the state by applying the provided transformation block.
     * Typically used to update the state in response to a domain event.
     *
     * @param block Lambda that computes the new state from the current one.
     **/
    @TransactionSenderDslMarker
    protected suspend fun reduceState(
        block: (State) -> State,
    ) = sendTransaction(Transaction.UpdateState(block))

    /**
     * Emits a side effect to be processed, such as UI toasts, dialogs, etc.
     *
     * @param effect The side effect to emit.
     **/
    @TransactionSenderDslMarker
    protected suspend fun reduceSideEffect(
        effect: SideEffect,
    ) = sendTransaction(Transaction.SendSideEffect(effect))

    /**
     * Emits a side effect built from the given lambda to be processed, such as UI toasts, dialogs, etc.
     *
     * @param block Lambda that produces the side effect.
     **/
    @TransactionSenderDslMarker
    protected suspend fun reduceSideEffect(
        block: () -> SideEffect,
    ) = reduceSideEffect(block.invoke())

    private suspend fun sendTransaction(
        transaction: Transaction<State, SideEffect, Nothing, DomainEvent>,
    ) = transactionChannel.send(transaction)

}
