package ru.whoame.recogniser.ui.viewmodel.handler

import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.receiveAsFlow
import ru.whoame.recogniser.ui.viewmodel.contracts.Transaction
import ru.whoame.recogniser.ui.viewmodel.utils.TransactionSenderDslMarker

/**
 * Abstract base class for handling UI events within a state machine architecture.
 * Provides mechanisms to update state, send side effects,
 * and emit domain events using coroutine-based transactions.
 *
 * @param State The type representing the state.
 * @param SideEffect The type representing UI or other indirect actions triggered by events.
 * @param UiEvent The type representing incoming UI events.
 * @param DomainEvent The type representing domain events triggered from UI interactions.
 **/
abstract class BaseUiEventHandler<State : Any, SideEffect : Any, UiEvent : Any, DomainEvent : Any> {

    private val transactionChannel: Channel<Transaction<State, SideEffect, UiEvent, DomainEvent>> = Channel()

    /**
     * Flow of all transactions generated by state, side effect, or domain event changes.
     * These transactions are intended to be processed by observers of the state machine.
     **/
    val transactionFlow: Flow<Transaction<State, SideEffect, UiEvent, DomainEvent>>
        get() = transactionChannel.receiveAsFlow()

    /**
     * Processes an incoming UI event and returns a cold [Flow].
     * The data from this [Flow] is completely ignored.
     * Subclasses should provide implementation
     * that determines how each event affects state, side effects, and/or domain events.
     *
     * Use reduceState functions to update state, reduceSideEffect functions to send side effects,
     * and reduceEvent functions to emit domain events.
     * These send data to the channel that handles updates.
     *
     * @param event Incoming UI-specific event to handle.
     *
     * @return [Flow] that produces results, the result itself is completely ignored.
     **/
    abstract fun handleEvent(event: UiEvent): Flow<*>

    /**
     * Reduces (updates) the state by applying the provided transformation block.
     * Typically used to update the state in response to a UI event.
     *
     * @param block Lambda that computes the new state from the current one.
     **/
    @TransactionSenderDslMarker
    protected suspend fun reduceState(
        block: (State) -> State,
    ) = sendTransaction(Transaction.UpdateState(block))

    /**
     * Emits a side effect to be processed, such as UI toasts, dialogs, etc.
     *
     * @param effect The side effect to emit.
     **/
    @TransactionSenderDslMarker
    protected suspend fun reduceSideEffect(
        effect: SideEffect,
    ) = sendTransaction(Transaction.SendSideEffect(effect))

    /**
     * Emits a side effect built from the given lambda to be processed, such as UI toasts, dialogs, etc.
     *
     * @param block Lambda that produces the side effect.
     **/
    @TransactionSenderDslMarker
    protected suspend fun reduceSideEffect(
        block: () -> SideEffect,
    ) = reduceSideEffect(block.invoke())

    /**
     * Emits a domain event directly to be processed by domain logic.
     *
     * @param event The domain event to emit.
     *
     * @see BaseDomainEventHandler
     **/
    @TransactionSenderDslMarker
    protected suspend fun reduceEvent(
        event: DomainEvent,
    ) = sendTransaction(Transaction.SendDomainEvent(event))

    /**
     * Emits a domain event built from the given lambda to be processed by domain logic.
     *
     * @param block Lambda that produces the domain event.
     **/
    @TransactionSenderDslMarker
    protected suspend fun reduceEvent(
        block: () -> DomainEvent,
    ) = reduceEvent(block.invoke())

    private suspend fun sendTransaction(
        transaction: Transaction<State, SideEffect, UiEvent, DomainEvent>,
    ) = transactionChannel.send(transaction)

}
