package ru.whoame.state_machine.handler

import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.receiveAsFlow
import ru.whoame.state_machine.contract.Transaction
import ru.whoame.state_machine.utils.TransactionSenderDslMarker

/**
 * Abstract base class for handling domain events within a state machine architecture.
 * Provides mechanisms to update state and send side effects using coroutine-based transactions.
 *
 * @param State The type representing the state.
 * @param SideEffect The type representing UI or other indirect actions triggered by events.
 * @param DomainEvent The type representing incoming domain events.
 **/
abstract class BaseDomainEventHandler<State : Any, SideEffect : Any, DomainEvent : Any> {

    private val transactionChannel: Channel<Transaction<State, SideEffect, Nothing, DomainEvent>> = Channel()

    /**
     * Flow of all transactions generated by state or side effect changes.
     * These transactions are intended to be processed by observers of the state machine.
     **/
    internal val transactionFlow: Flow<Transaction<State, SideEffect, Nothing, DomainEvent>>
        get() = transactionChannel.receiveAsFlow()

    private lateinit var stateFlow: StateFlow<State>

    /**
     * Sets the state flow for this handler.
     * This method is intended for internal use by the state machine framework.
     *
     * @param flow The StateFlow to be used for state management.
     **/
    internal fun setStateFlow(flow: StateFlow<State>) {
        stateFlow = flow
    }

    /**
     * The current state value.
     * Provides direct access to the current state without needing to collect from the flow.
     **/
    protected val state: State get() = stateFlow.value

    /**
     * Processes an incoming domain event and returns a cold [Flow].
     * The data from this [Flow] is completely ignored. Only the side effects matter.
     * Subclasses should provide an implementation that determines how each event affects state and/or side effects.
     *
     * Use [reduceState] functions to update state, and use [reduceSideEffect] functions to send side effects.
     * These functions send data to the channel that handles the updates.
     *
     * @param event The incoming domain-specific event to handle.
     *
     * @return A [Flow] that produces results. The result itself is completely ignored.
     **/
    abstract fun handleEvent(event: DomainEvent): Flow<*>

    /**
     * Reduces (updates) the state by applying the provided transformation block.
     * Typically used to update the state in response to a domain event.
     *
     * @param block A lambda that computes the new state from the current one.
     **/
    @TransactionSenderDslMarker
    protected suspend fun reduceState(
        block: (State) -> State,
    ) = sendTransaction(Transaction.StateUpdate(block))

    /**
     * Emits a side effect to be processed, such as UI toasts, dialogs, navigation, etc.
     *
     * @param effect The side effect to emit.
     **/
    @TransactionSenderDslMarker
    protected suspend fun reduceSideEffect(
        effect: SideEffect,
    ) = sendTransaction(Transaction.SideEffect(effect))

    /**
     * Emits a side effect built from the given lambda to be processed, such as UI toasts, dialogs, navigation, etc.
     *
     * @param block A lambda that produces the side effect.
     **/
    @TransactionSenderDslMarker
    protected suspend fun reduceSideEffect(
        block: () -> SideEffect,
    ) = reduceSideEffect(block.invoke())

    /**
     * Sends a transaction to the transaction channel for processing.
     *
     * @param transaction The transaction to send.
     **/
    private suspend fun sendTransaction(
        transaction: Transaction<State, SideEffect, Nothing, DomainEvent>,
    ) = transactionChannel.send(transaction)

}
